jest.mock('fs/promises', () => ({
  readdir: jest.fn(),
  writeFile: jest.fn().mockResolvedValue(undefined),
}));

import { generateManifest } from '@/cli/build';
import { readdir, writeFile } from 'fs/promises';

const mockReaddir = readdir as jest.Mock;
const mockWriteFile = writeFile as jest.Mock;

function file(name: string) {
  return { name, isDirectory: () => false };
}

function dir(name: string) {
  return { name, isDirectory: () => true };
}

const ROUTES = '/fake/routes';

beforeEach(() => {
  mockReaddir.mockResolvedValue([]);
  mockWriteFile.mockResolvedValue(undefined);
});

afterEach(() => {
  jest.clearAllMocks();
});

describe('generateManifest — output file', () => {
  it('writes _manifest.ts inside routesDir', async () => {
    await generateManifest(ROUTES);
    expect(mockWriteFile).toHaveBeenCalledWith(
      `${ROUTES}/_manifest.ts`,
      expect.any(String),
      'utf-8',
    );
  });

  it('includes the auto-generated header comment', async () => {
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('AUTO-GENERATED by lacis build');
  });

  it('always emits the routes export even when no routes exist', async () => {
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('export const routes = [');
  });

  it('always emits the middlewares export even when no middleware files exist', async () => {
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('export const middlewares = [');
  });

  it('does not emit import statements when there are no routes or middleware files', async () => {
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).not.toContain('import *');
  });
});

describe('generateManifest — route discovery', () => {
  it('discovers a root index.ts and maps it to "/"', async () => {
    mockReaddir.mockResolvedValue([file('index.ts')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/'");
    expect(content).toContain("'./index.js'");
  });

  it('discovers a root index.js as well', async () => {
    mockReaddir.mockResolvedValue([file('index.js')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/'");
  });

  it('discovers a nested route and maps directory name to the path segment', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('users')]);
      if (d.endsWith('/users')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/users'");
    expect(content).toContain("'./users/index.js'");
  });

  it('converts [param] directory names to :param route segments', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('[id]')]);
      if (d.endsWith('/[id]')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/:id'");
  });

  it('converts [...param] catch-all directory names to a * wildcard segment', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('files')]);
      if (d.endsWith('/files')) return Promise.resolve([dir('[...path]')]);
      if (d.endsWith('/[...path]')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/files/*'");
  });

  it('converts [param?] to :param (optional param syntax)', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('[slug?]')]);
      if (d.endsWith('/[slug?]')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/:slug'");
  });

  it('discovers multiple routes and imports each with a unique binding', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([file('index.ts'), dir('api')]);
      if (d.endsWith('/api')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("_route_0");
    expect(content).toContain("_route_1");
  });

  it('skips directories whose names start with "+"', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES)
        return Promise.resolve([dir('+layout'), file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    const routeCount = (content.match(/path:/g) ?? []).length;
    expect(routeCount).toBe(1); // only the root route, not +layout
  });

  it('handles an unreadable routesDir gracefully and still writes an empty manifest', async () => {
    mockReaddir.mockRejectedValue(new Error('ENOENT'));
    await expect(generateManifest(ROUTES)).resolves.toBeUndefined();
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('export const routes = [');
    expect(content).toContain('export const middlewares = [');
    expect(content).not.toContain('_route_');
    expect(content).not.toContain('_mw_');
  });
});

describe('generateManifest — middleware discovery', () => {
  it('discovers a +middleware.global.ts at the root and emits it as cascade', async () => {
    mockReaddir.mockResolvedValue([file('+middleware.global.ts')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("type: 'cascade'");
    expect(content).toContain("path: '/'");
    expect(content).toContain("'./+middleware.global.js'");
  });

  it('discovers a +middleware.ts at the root and emits it as exact', async () => {
    mockReaddir.mockResolvedValue([file('+middleware.ts')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("type: 'exact'");
    expect(content).toContain("path: '/'");
    expect(content).toContain("'./+middleware.js'");
  });

  it('discovers middleware in a subdirectory with the correct path', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('api')]);
      if (d.endsWith('/api')) return Promise.resolve([file('+middleware.global.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/api'");
    expect(content).toContain("type: 'cascade'");
  });

  it('can discover both cascade and exact middleware in the same directory', async () => {
    mockReaddir.mockResolvedValue([file('+middleware.global.ts'), file('+middleware.ts')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("type: 'cascade'");
    expect(content).toContain("type: 'exact'");
    expect((content.match(/_mw_/g) ?? []).length).toBeGreaterThanOrEqual(4); // 2 imports + 2 entries
  });

  it('prefers .ts over .js for middleware files', async () => {
    mockReaddir.mockResolvedValue([file('+middleware.global.ts'), file('+middleware.global.js')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    const mwImportCount = (content.match(/import \* as _mw_/g) ?? []).length;
    expect(mwImportCount).toBe(1);
  });

  it('emits unique binding names for each middleware file', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([file('+middleware.global.ts'), dir('api')]);
      if (d.endsWith('/api')) return Promise.resolve([file('+middleware.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('_mw_0');
    expect(content).toContain('_mw_1');
  });
});
