jest.mock('fs/promises', () => ({
  readdir: jest.fn(),
  writeFile: jest.fn().mockResolvedValue(undefined),
  mkdir: jest.fn().mockResolvedValue(undefined),
  rm: jest.fn().mockResolvedValue(undefined),
}));

import { generateRouteTypes } from '@/cli/build';
import { readdir, writeFile, rm } from 'fs/promises';

const mockReaddir = readdir as jest.Mock;
const mockWriteFile = writeFile as jest.Mock;
const mockRm = rm as jest.Mock;

const file = (name: string) => ({ name, isDirectory: () => false });
const dir = (name: string) => ({ name, isDirectory: () => true });

beforeEach(() => {
  jest.clearAllMocks();
  mockWriteFile.mockResolvedValue(undefined);
  // routes/ (index), routes/users/[id]/ (index), routes/posts/[slug?]/ (index)
  mockReaddir.mockImplementation(async (d: string) => {
    if (d === 'routes') return [file('index.ts'), dir('users'), dir('posts'), dir('+middleware.ts' as any)];
    if (d === 'routes/users') return [dir('[id]')];
    if (d === 'routes/users/[id]') return [file('index.ts')];
    if (d === 'routes/posts') return [dir('[slug?]')];
    if (d === 'routes/posts/[slug?]') return [file('index.ts')];
    return [];
  });
});

function writtenFor(suffix: string): string {
  const call = mockWriteFile.mock.calls.find(([p]) => (p as string).replace(/\\/g, '/').endsWith(suffix));
  if (!call) throw new Error(`no $types written for ${suffix}`);
  return call[1] as string;
}

describe('generateRouteTypes', () => {
  it('wipes the generated dir before writing', async () => {
    await generateRouteTypes('routes');
    expect(mockRm).toHaveBeenCalledWith(expect.stringContaining('.lacis/types'.replace('/', require('path').sep)), { recursive: true, force: true });
  });

  it('generates one $types per route that has an index', async () => {
    await generateRouteTypes('routes');
    // routes/, routes/users/[id]/, routes/posts/[slug?]/  → 3
    expect(mockWriteFile).toHaveBeenCalledTimes(3);
  });

  it('types a required param from [id]', async () => {
    await generateRouteTypes('routes');
    const content = writtenFor('routes/users/[id]/$types.d.ts');
    expect(content).toContain('export type RouteParams = { id: string }');
    expect(content).toContain('export type RouteHandler =');
    expect(content).toContain('AUTO-GENERATED by lacis');
  });

  it('types an optional param from [slug?]', async () => {
    await generateRouteTypes('routes');
    const content = writtenFor('routes/posts/[slug?]/$types.d.ts');
    expect(content).toContain('export type RouteParams = { slug?: string }');
  });

  it('emits empty params for a static route', async () => {
    await generateRouteTypes('routes');
    const content = writtenFor('routes/$types.d.ts');
    expect(content).toContain('export type RouteParams = Record<string, never>');
  });

  it('types the catch-all remainder under "*" for a [...param] route', async () => {
    mockReaddir.mockImplementation(async (d: string) => {
      if (d === 'routes') return [dir('files')];
      if (d === 'routes/files') return [dir('[...path]')];
      if (d === 'routes/files/[...path]') return [file('index.ts')];
      return [];
    });
    await generateRouteTypes('routes');
    const content = writtenFor('routes/files/[...path]/$types.d.ts');
    expect(content).toContain('export type RouteParams = { "*": string }');
  });
});
