import { readdir, writeFile, unlink, mkdir, rm } from 'fs/promises'
import { join, relative, resolve, dirname } from 'path'
import { spawn } from 'child_process'
import { existsSync, readFileSync } from 'fs'

interface DiscoveredRoute {
  importPath: string
  routePath: string
}

interface DiscoveredMiddleware {
  importPath: string
  routePath: string
  type: 'cascade' | 'exact'
}

async function discoverRoutes(routesDir: string): Promise<DiscoveredRoute[]> {
  const routes: DiscoveredRoute[] = []

  async function scan(dir: string, pathSegments: string[] = []) {
    let entries
    try {
      entries = await readdir(dir, { withFileTypes: true })
    } catch {
      return
    }

    const indexFile = entries.find(
      (e) => !e.isDirectory() && (e.name === 'index.ts' || e.name === 'index.js')
    )

    if (indexFile) {
      const importPath =
        './' + relative(routesDir, join(dir, indexFile.name)).replace(/\\/g, '/').replace(/\.ts$/, '.js')
      const routePath =
        '/' +
        pathSegments
          .map((s) => (/^\[\.\.\.\w+\]$/.test(s) ? '*' : s.replace(/^\[(\w+)\??\]$/, ':$1')))
          .join('/')
      routes.push({ importPath, routePath: routePath === '//' ? '/' : routePath })
    }

    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith('+')) {
        await scan(join(dir, entry.name), [...pathSegments, entry.name])
      }
    }
  }

  await scan(routesDir)
  return routes
}

async function discoverMiddlewares(routesDir: string): Promise<DiscoveredMiddleware[]> {
  const middlewares: DiscoveredMiddleware[] = []

  async function scan(dir: string, routePath: string) {
    let entries
    try {
      entries = await readdir(dir, { withFileTypes: true })
    } catch {
      return
    }

    const cascadeFile =
      entries.find((e) => e.name === '+middleware.global.ts') ??
      entries.find((e) => e.name === '+middleware.global.js')
    if (cascadeFile) {
      middlewares.push({
        importPath: './' + relative(routesDir, join(dir, cascadeFile.name)).replace(/\\/g, '/').replace(/\.ts$/, '.js'),
        routePath,
        type: 'cascade',
      })
    }

    const exactFile =
      entries.find((e) => e.name === '+middleware.ts') ??
      entries.find((e) => e.name === '+middleware.js')
    if (exactFile) {
      middlewares.push({
        importPath: './' + relative(routesDir, join(dir, exactFile.name)).replace(/\\/g, '/').replace(/\.ts$/, '.js'),
        routePath,
        type: 'exact',
      })
    }

    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith('+')) {
        const childPath = routePath === '/' ? `/${entry.name}` : `${routePath}/${entry.name}`
        await scan(join(dir, entry.name), childPath)
      }
    }
  }

  await scan(routesDir, '/')
  return middlewares
}

export async function generateManifest(routesDir: string): Promise<void> {
  const [routes, middlewares] = await Promise.all([
    discoverRoutes(routesDir),
    discoverMiddlewares(routesDir),
  ])

  const routeImports = routes
    .map((r, i) => `import * as _route_${i} from '${r.importPath}'`)
    .join('\n')

  const mwImports = middlewares
    .map((m, i) => `import * as _mw_${i} from '${m.importPath}'`)
    .join('\n')

  const allImports = [routeImports, mwImports].filter(Boolean).join('\n')

  const routeEntries = routes
    .map((r, i) => `  { path: '${r.routePath}', handlers: _route_${i} }`)
    .join(',\n')

  const mwEntries = middlewares
    .map((m, i) => `  { path: '${m.routePath}', type: '${m.type}', module: _mw_${i} }`)
    .join(',\n')

  const content = [
    '// AUTO-GENERATED by lacis build — do not edit',
    allImports,
    '',
    'export const routes = [',
    routeEntries,
    ']',
    '',
    'export const middlewares = [',
    mwEntries,
    ']',
    '',
  ].join('\n')

  await writeFile(join(routesDir, '_manifest.ts'), content, 'utf-8')
  console.log(`[lacis] Generated manifest with ${routes.length} route(s) and ${middlewares.length} middleware(s)`)
}

// Per-route generated types ($types). Each route folder gets a mirrored
// `.lacis/types/<path>/$types.d.ts` with its params typed from the folder names
// ([id] -> string, [id?] -> optional). A tsconfig `rootDirs: [".", "./.lacis/types"]`
// makes a route's `import type { RouteHandler } from './$types'` resolve to it.
function paramsTypeLiteral(segments: string[]): string {
  const params = segments
    .map((s) => s.match(/^\[(\w+)(\?)?\]$/))
    .filter((m): m is RegExpMatchArray => m !== null)
    .map((m) => ({ name: m[1], optional: m[2] === '?' }))
  // [...name] catch-all segments surface the remainder under the "*" key at runtime
  const hasWildcard = segments.some((s) => /^\[\.\.\.\w+\]$/.test(s))
  const entries = params.map((p) => `${p.name}${p.optional ? '?' : ''}: string`)
  if (hasWildcard) entries.push(`"*": string`)
  if (entries.length === 0) return 'Record<string, never>'
  return '{ ' + entries.join('; ') + ' }'
}

function routeTypesContent(paramsLiteral: string): string {
  return [
    '// AUTO-GENERATED by lacis — do not edit.',
    "import type { Request, Response } from 'lacis'",
    '',
    `export type RouteParams = ${paramsLiteral}`,
    "export type RouteRequest = Omit<Request, 'params'> & { params: RouteParams }",
    'export type RouteHandler = (req: RouteRequest, res: Response) => void | Promise<void>',
    '',
  ].join('\n')
}

export async function generateRouteTypes(routesDir: string): Promise<void> {
  const cwd = process.cwd()
  const typesRoot = join(cwd, '.lacis', 'types')
  await rm(typesRoot, { recursive: true, force: true })

  let count = 0
  async function scan(dir: string, segments: string[]) {
    let entries
    try {
      entries = await readdir(dir, { withFileTypes: true })
    } catch {
      return
    }

    const hasIndex = entries.some(
      (e) => !e.isDirectory() && (e.name === 'index.ts' || e.name === 'index.js')
    )
    if (hasIndex) {
      const rel = relative(cwd, resolve(dir)).replace(/\\/g, '/')
      const outPath = join(typesRoot, rel, '$types.d.ts')
      await mkdir(dirname(outPath), { recursive: true })
      await writeFile(outPath, routeTypesContent(paramsTypeLiteral(segments)), 'utf-8')
      count++
    }

    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith('+')) {
        await scan(join(dir, entry.name), [...segments, entry.name])
      }
    }
  }

  await scan(routesDir, [])
  console.log(`[lacis] Generated $types for ${count} route(s)`)
}

type BuildPlatform = 'bun' | 'node' | 'vercel' | 'netlify' | 'cloudflare'

function detectPlatform(cwd: string): BuildPlatform {
  if (existsSync(join(cwd, 'wrangler.toml'))) return 'cloudflare'
  if (existsSync(join(cwd, 'netlify.toml'))) return 'netlify'
  if (existsSync(join(cwd, 'vercel.json'))) return 'vercel'

  try {
    const pkg = JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf-8')) as {
      dependencies?: Record<string, string>
      devDependencies?: Record<string, string>
    }
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies }
    if (allDeps['wrangler']) return 'cloudflare'
    if (allDeps['@netlify/functions'] || allDeps['netlify-cli']) return 'netlify'
    if (allDeps['vercel'] || allDeps['@vercel/node']) return 'vercel'
  } catch {}

  if ((process.versions as Record<string, string | undefined>).bun !== undefined) return 'bun'
  if (existsSync(join(cwd, 'bun.lockb')) || existsSync(join(cwd, 'bun.lock'))) return 'bun'

  return 'node'
}

function findEntry(cwd: string): string | null {
  try {
    const pkg = JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf-8')) as {
      module?: unknown
      main?: unknown
    }
    const candidate = pkg.module ?? pkg.main
    if (typeof candidate === 'string' && existsSync(join(cwd, candidate))) return candidate
  } catch {}

  for (const name of ['server.ts', 'index.ts', 'app.ts', 'main.ts']) {
    if (existsSync(join(cwd, name))) return name
  }

  return null
}

function getTsConfigOutDir(cwd: string): string | null {
  try {
    const tsconfig = JSON.parse(readFileSync(join(cwd, 'tsconfig.json'), 'utf-8')) as {
      compilerOptions?: { outDir?: string }
    }
    return tsconfig.compilerOptions?.outDir ?? null
  } catch {
    return null
  }
}

async function findTsFiles(dir: string): Promise<string[]> {
  const files: string[] = []
  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return files
  }
  for (const entry of entries) {
    if (entry.isDirectory()) {
      files.push(...await findTsFiles(join(dir, entry.name)))
    } else if (entry.name.endsWith('.ts') && entry.name !== '_manifest.ts') {
      files.push(join(dir, entry.name))
    }
  }
  return files
}

async function findFile(dir: string, name: string): Promise<string | null> {
  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return null
  }
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      const found = await findFile(full, name)
      if (found) return found
    } else if (entry.name === name) {
      return full
    }
  }
  return null
}

function spawnAsync(cmd: string, args: string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { stdio: 'inherit', cwd })
    child.on('close', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${cmd} exited with code ${code}`))
    })
    child.on('error', (err: NodeJS.ErrnoException) => {
      if (err.code === 'ENOENT') reject(new Error(`Command not found: ${cmd}. Make sure it is installed.`))
      else reject(err)
    })
  })
}

export async function build(routesDir: string, entry?: string): Promise<void> {
  const cwd = process.cwd()
  const platform = detectPlatform(cwd)
  const manifestPath = join(routesDir, '_manifest.ts')
  let outDir = 'dist'

  await generateManifest(routesDir)
  await generateRouteTypes(routesDir)

  // Vercel/Netlify/Cloudflare manage their own compilation pipeline; the manifest is all they need.
  if (platform === 'vercel' || platform === 'netlify' || platform === 'cloudflare') {
    console.log(`[lacis] ${platform} detected — manifest generated, platform handles compilation`)
    return
  }

  try {
    if (platform === 'bun') {
      const resolvedEntry = entry ?? findEntry(cwd)
      if (!resolvedEntry) throw new Error('Entry point not found. Specify one with --entry <file>.')

      const routeFiles = await findTsFiles(routesDir)
      const allFiles = [join(cwd, resolvedEntry), manifestPath, ...routeFiles]

      // Use Bun.build() JS API — external:'*' gives transpile-only behavior,
      // root preserves directory structure in outdir. Avoids CLI --outdir bug.
      const result = await (globalThis as any).Bun.build({
        entrypoints: allFiles,
        outdir: join(cwd, 'dist'),
        root: cwd,
        external: ['*'],
        target: 'bun',
      })
      if (!result.success) {
        const msgs: string = result.logs.map((l: any) => l.message ?? String(l)).join('\n')
        throw new Error(`Bun build failed:\n${msgs}`)
      }
    } else {
      const tscBin = join(cwd, 'node_modules', '.bin', 'tsc')
      if (!existsSync(tscBin)) {
        throw new Error(
          'TypeScript not found. Add it to your project: npm install --save-dev typescript'
        )
      }
      outDir = getTsConfigOutDir(cwd) ?? 'dist'
      await spawnAsync(tscBin, ['--outDir', outDir], cwd)
    }
  } finally {
    // Manifest is a build artifact — remove it from source after compilation
    await unlink(manifestPath).catch(() => {})
  }

  // The serverless adapters import routes/_manifest.js from the compiled output.
  // tsc obeys the project's tsconfig, so noEmit / a narrow `include` / an unexpected
  // rootDir can silently produce nothing — fail loudly instead of a green build log.
  const compiledManifest = await findFile(join(cwd, outDir), '_manifest.js')
  if (!compiledManifest) {
    throw new Error(
      `Build produced no _manifest.js under "${outDir}/". The compiler ran but emitted nothing for the manifest — ` +
        `check that your tsconfig does not set "noEmit": true and that "include" covers your routes directory.`
    )
  }

  console.log(`[lacis] Build complete → ${outDir}/`)
}
